CREATE DATABASE IF NOT EXISTS `blog_db`;
USE `blog_db`;

CREATE TABLE IF NOT EXISTS `blogs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `blog_name` VARCHAR(255) NOT NULL,
  `blog_slug` VARCHAR(255) NOT NULL,
  `blog_content` TEXT NOT NULL,
  `added_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;